### ISSUE TITLE
How to get 'padded.dat' in bert.py when constructing graph

### ISSUE THREAD

**Issue by LeslieHoloway** [EmmaRocheteau/eICU-GNN-LSTM#1]
When using the following scipt to make the graphs, a FileNotFoundError encountered.
`python3 -m graph_construction.bert`

In graph_construction/bert.py, `padded.dat` and `attention_mask.dat` are needed.
```
def read_data(graph_dir):
    padded = np.memmap(graph_dir + 'padded.dat', dtype=int, shape=(89123, 512))
    attention_mask = np.memmap(graph_dir + 'attention_mask.dat', dtype=int, shape=(89123, 512))
    input_ids = torch.tensor(padded).to('cuda')
    attn_mask = torch.tensor(attention_mask).to('cuda')
    return input_ids, attn_mask
```
How to generate padded.dat and attention_mask.dat? I am curious about how to use bert to analyze the EHR data. Could you share the related code? Thank you very much.

**Comment by EmmaRocheteau** [comment]
Hello! Sorry it took a while to respond as it was the weekend. If you would like access to the graphs without needing those files, you can just download it by request from here: https://drive.google.com/drive/folders/1yWNLhGOTPhu6mxJRjKCgKRJCJjuToBS4?usp=sharing

To make those files from scratch, you would need to run eICU-GNN-LSTM/src/dataloader/convert.py. I will add that to the documentation!

Let us know if you have any other problems
