### ISSUE TITLE
Diagnoses.sql

### ISSUE THREAD

**Issue by sherry6247** [EmmaRocheteau/eICU-GNN-LSTM#2]
following the README, when I run the script of `creat_all_tables.sql`, I got a Null table of Diagnoses. 
When checking the Diagnoses.sql. In line 40 of Diagnoses.sql. it seems to have a spelling error, I trans the `lb_labels` to `labels`. it works!

**Comment by EmmaRocheteau** [comment]
Thank you for letting me know! Sorry for the typo. I just changed the master file so it should work for people in future.
